---
apiVersion: v1
kind: Pod 
metadata: 
  name: secret-cm-v
  labels:
    app: demo-v
spec:
  containers: 
    - name: demo-v
      image: nginx
      volumeMounts: 
        - name: user-name-v
          mountPath: /credentials/username
        - name: password-v
          mountPath: /credentials/password
  volumes: 
    - name: user-name-v
      configMap: 
        name: user-name
    - name: password-v
      secret: 
        secretName: password