---
apiVersion: v1 
kind: Service
metadata:
  name: http-svc-demo
  labels:
    app: httpd
spec:
  type: NodePort
  selector: 
   app: httpd
  ports: 
    - targetPort: 80
      port: 443 
      nodePort: 32000