---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: httpd-svc-rs
  labels: 
    app: httpd 
spec:
  minReadySeconds: 5
  replicas: 3
  selector: 
    matchLabels: 
      app: httpd 
  template: 
    metadata:
      labels:
        app: httpd 
    spec: 
      containers: 
        - name: httpd-svc 
          image: httpd:2
          ports: 
            - containerPort: 80
              protocol: TCP