---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-labels1
  labels:
    app: web-server
    env: dev
    release: v1.0
spec: 
  containers:
    - name: my-nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
          protocol: "TCP"
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-labels2
  labels: 
    app: web-server
    env: qt
    release: v1.1
spec: 
  containers:
    - name: my-ngnix-2
      image: nginx:1.27
      ports:
        - containerPort: 80
          protocol: "TCP"

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-labels3
  labels: 
    app: web-server
    env: uat
    release: v1.2
spec: 
  containers:
    - name: my-ngnix-3
      image: nginx:1.27
      ports: 
        - containerPort: 80
          protocol: "TCP"
