---
apiVersion: v1
kind: Service
metadata: 
   name: nginx-svc
   labels: 
     app: nginx
     purpose: service 
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports: 
    - targetPort: 80
      port: 80
      

 
