---
apiVersion: v1 
kind: Namespace
metadata:
  name: dev

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-1
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "image updated to v2"
spec:
  minReadySeconds: 5
  replicas: 6
  selector: 
    matchLabels: 
      app: webapp
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template: 
    metadata: 
      labels: 
        app: webapp
    spec: 
      containers: 
        - name: web-app-deployment
          image: saikrishna38721/a1:v2
          ports:
            - name: web-app
              containerPort: 80
              protocol: TCP
