---
apiVersion: v1
kind: Pod
metadata:
  name: init-container
  labels: 
    purpose: init
spec: 
  initContainers: 
    - name: init-container
      image: alpine
      command:
        - sleep
        - 15s
  containers: 
    - name: main-container
      image: nginx:1.25