---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-matchexpression-rs
  labels: 
    app: jenkins-me-rs
spec: 
  minReadySeconds: 5
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - jenkins
          - hudson
      - key: release
        operator: Exists
  template: 
    metadata: 
      labels:
        app: jenkins
        release: v1.0
    spec:
      containers: 
        - name: jenkins
          image: jenkins/jenkins
          ports: 
            - containerPort: 8080
              protocol: TCP